### PR TITLE
Add Tomas Coufal as tumido

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
Not sure how to obtain the gchat id.

**Comment by harshad16** [comment]
> Not sure how to obtain the gchat id.

I will get that and sync with this.

**Comment by harshad16** [comment]
thanks :taco:

**Comment by fridex** [comment]
> > Not sure how to obtain the gchat id.
> 
> I will get that and sync with this.

Cool, thanks! :+1:

**Pull request merged**
